### PR TITLE
Add normalizeConnectArgs from Node v6

### PR DESCRIPTION
**Pull request by sam3d**
The latest versions of Node don't include the `net._normalizeConnectArgs` method. I've included it exactly as it was in that Node.js version so that `node-serf` is now compatible with up to `Node v8.7.0`, as far as I can tell.

Awesome project by the way, thank you for your hard work! :)

### CODE REVIEW

**Comment by zbjornson** [comment]
Thanks, looks like it was renamed to `_normalizeArgs` in [this commit](https://github.com/nodejs/node/commit/fd6af98c2d623c87f910437086ea04c7be195df8#diff-e6ef024c3775d787c38487a6309e491d). Either way it's better to not use an undocumented API, so +1.

Might want to add a comment attributing that function to Node.js/Node.js contributors.

Not sure what happened to circleci. It's not even queued.

**Comment by sam3d** [comment]
Added the attribution and rebased. Didn't realise they had just changed the name, but yeah good call on that 👍 

Weird with CircleCI, doesn't seem to actually be running it at all.

**Comment by zbjornson** [comment]
Thanks. Can you push to your branch again please (e.g. `git commit --amend --no-edit; git push -f`) to try to trigger a build? I think I fixed the CI setting, but I can't trigger the build.

**Comment by zbjornson** [comment]
Woo, CI ran 🎉 but some linter failures.

After that's fixed this looks good to me. Will leave open 'till tomorrow to given @hden a chance to look.

**Comment by hden** [comment]
The function `isPipeName` is not defined, so we probably need to port that too.

**Comment by sam3d** [comment]
Fixed the linter errors and added the two missing functions `isPipeName` and the subsequent `toNumber` that it uses. Should hopefully be good to go :)

**Comment by hden** [comment]
LGTM

**Pull request merged**
